include: package:lints/recommended.yaml 

analyzer:
  # This is not a flutter project, but the best example is
  # using flutter so I made a flutter example and will ignore
  # it in analysis to not get error because of flutter dependencies
  # that don't exist in this dart project
  exclude: [example/example.dart]