name: dart_debouncer
description: "A package for creating debounce in dart will possibilities of multi instances debounce. No singleton pattern"
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
